name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      # - name: Run tests with coverage
      #   run: flutter test --coverage

      # - name: Generate Dart analysis report
      #   run: dartanalyzer --format json --no-hints lib > build/reports/dart/dart-report.json

      - name: Install SonarScanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip sonar-scanner-cli-4.6.2.2472-linux.zip -d $HOME/
          echo 'export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Verify SonarScanner Installation
        run: sonar-scanner --version

      - name: Run SonarScanner
        run: sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
